#!/usr/bin/env sh
set -eu

cat > js/firebase-config.js <<EOF
window.REFLEX_FIREBASE_CONFIG = {
    apiKey: "${REFLEX_PUBLIC_FIREBASE_API_KEY:-${REFLEX_FIREBASE_API_KEY:-}}",
    authDomain: "${REFLEX_PUBLIC_FIREBASE_AUTH_DOMAIN:-${REFLEX_FIREBASE_AUTH_DOMAIN:-}}",
    databaseURL: "${REFLEX_PUBLIC_FIREBASE_DATABASE_URL:-${REFLEX_FIREBASE_DATABASE_URL:-}}",
    projectId: "${REFLEX_PUBLIC_FIREBASE_PROJECT_ID:-${REFLEX_FIREBASE_PROJECT_ID:-}}",
    storageBucket: "${REFLEX_PUBLIC_FIREBASE_STORAGE_BUCKET:-${REFLEX_FIREBASE_STORAGE_BUCKET:-}}",
    messagingSenderId: "${REFLEX_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:-${REFLEX_FIREBASE_MESSAGING_SENDER_ID:-}}",
    appId: "${REFLEX_PUBLIC_FIREBASE_APP_ID:-${REFLEX_FIREBASE_APP_ID:-}}",
    measurementId: "${REFLEX_PUBLIC_FIREBASE_MEASUREMENT_ID:-${REFLEX_FIREBASE_MEASUREMENT_ID:-}}",
};
EOF
